### ISSUE TITLE
Access node_modules outside of app

### ISSUE THREAD

**Issue by iamdriz** [atom/asar#15]
According to this plugin for Grunt: https://www.npmjs.com/package/grunt-asar

You could have a separate asar archive for your app code and your node_modules.

So basically you could have a structure like:

~~~
package.json
Gruntfile.js
app
-- index.html
-- main.js
node_modules
-- grunt-asar
-- grunt-build-atom-shell
~~~

But how would you require node_modules from within the app folder that were up a level?

e.g.

~~~
var myPackage = require('package');
~~~

Could I do:

~~~
var myPackage = require('../package');
~~~

And what about when they are in an asar archive? So the structure is:

~~~
package.json
Gruntfile.js
app.asar
modules.asar
~~~

Could I do:

~~~
var myPackage = require('asar:/modules.asar/package');
~~~

**Comment by bwin** [comment]
Can this be closed?

**Comment by iamdriz** [comment]
Yes

**Comment by bwin** [comment]
thanks. @zcbenz you can close this
