### ISSUE TITLE
Why not using custom int64 representation?

### ISSUE THREAD

**Issue by OsamaAbbas** [atom/asar#17]
Hi there,

There are many libs which solve the accuracy problem while handling large integers in javascript.

Why don't you use one of them to remove the file size limit?

Examples:

https://github.com/candu/node-int64-native

https://github.com/broofa/node-int64

**Comment by bwin** [comment]
Do you have a problem with the file size limit or is this theoretical?

**Comment by OsamaAbbas** [comment]
I don't have a problem for now. It is just an enhancement.

**Comment by zcbenz** [comment]
Node's `fs.Stats` uses JavaScript Number for `size`, which can not be converted to uint64 safely, so unless we rewrite the file related functions ourselves, it is not safe to handle file sizes larger than 4.2GB.

**Comment by bwin** [comment]
Actually I think the "safe limit" limit is higher, but zcbenz is right -> the `fs` functions expect/return js-numbers as size/offset.

**Comment by OsamaAbbas** [comment]
Is there a problem if the whole module('fs') was written for this purpose?

**Comment by bwin** [comment]
I don't understand, unless you mean **re**written. In that case, it wouldn't be worth the trouble IMHO. Asar is basically for packaging web-apps, so you gotta be doing some crazy stuff if you're hitting the size limit (whatever that may be, but *at least* 4.2GB). Even if, you could split that into many asar's.

**Comment by OsamaAbbas** [comment]
Yes I mean rewritten. Sorry!

You are right guys. Thank you. But I was thinking from an abstracted view of Asar as an alternative for tar.

**Comment by bwin** [comment]
BTW the max value for js numbers is `1 << 53` ~ 9PB.
I'm currently not 100% sure, if that means we can handle files of that size in every situation (but I think so).

But the asar limit is 4.2GB.

**Comment by zcbenz** [comment]
I did a search and found that there is `Number.MAX_SAFE_INTEGER` constant that represents the maximum safe integer which as @bwin said is `1 << 53`.

I think we can use `Number.MAX_SAFE_INTEGER` as the per file limit instead of 4.2GB.

**Comment by bwin** [comment]
But `Number.MAX_SAFE_INTEGER` is ECMAScript 6 only. So to use it, you have to define something yourself.
I played around (regarding #16) with the asar format at bwin/asar-util and this came up, too. But I need ca. 1 week for paid work. Then I get back to you.

**Comment by zcbenz** [comment]
Ah yeah, I didn't notice that.

And thanks for working on this!
