### ISSUE TITLE
Release extract command

### ISSUE THREAD

**Issue by joshuawarner32** [atom/asar#18]
Would it be possible to do an npm release (0.2.0?) with the code implementing the `extract` (whole archive) command, which is present in master?  That'd be really useful in my use-case.

**Comment by kevinsawicki** [comment]
Mind adding everyone on the core team as an owner in npmjs.org as well? Thanks

**Comment by zcbenz** [comment]
asar@0.2.0 has been published.

> Mind adding everyone on the core team as an owner in npmjs.org as well? Thanks

Done.

**Comment by bwin** [comment]
It doesn't really matter, but why 0.2.0 (instead of 0.1.3)?

**Comment by zcbenz** [comment]
@bwin Because we have added a new command, which I think belongs to "minor" instead of "patch".

**Comment by bwin** [comment]
First of all, I'm not arguing for or against anything here, it's really just a question. It's just for my understanding.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public 
API should not be considered stable.

That part of semver (above) and the way atom-shell handles things*, were the things that made me wonder.

\* = for example: 0.20.6 -> Add webFrame.registerUrlSchemeAsSecure API

**Comment by zcbenz** [comment]
In atom-shell, I tend to bump the minor version when there is a very big change, like a new Chrome upgrade, or some architecture change. If there is only a few lines' change, I would bump the patch version, even when it adds a new API. In this way I can let users know when we are having a significant update and they should test everything carefully.

For other projects, I would just follow the custom of the team.

**Comment by bwin** [comment]
Thanks for explaining.
