### ISSUE TITLE
unpacked files don't retain executable permission

### ISSUE THREAD

**Issue by kevinsawicki** [atom/asar#27]
If you have an executable file marked to be unpacked, it is not executable when put in the unpacked area.

**Comment by joernroeder** [comment]
i'm running into the same issue right now with electron 2.0.7 after adding the folderpath to my binaries into "asarUnpack" section in package.json.

`ls -l …/Contents/Resources/app.asar.unpacked/folder` gives me `-rw-r--r--`, source permissions are `-rwxr-xr-x`

**Comment by thinkclay** [comment]
I've been having the same issue for a binary in my archive. For my build and release process, I've been having to:

- manually unpack the asar
- Add execute permissions to my binary
- pack the asar again

Has anyone found a way to fix this with the standard build process?
