### ISSUE TITLE
Not running EXE files on app.asar.unpacked folder

### ISSUE THREAD

**Issue by luizlago** [atom/asar#47]
I'm trying to execute .exe file on my asar unpacked folder but not working. I unpacked one folder (app.asar.unpacked\public) and my executable is there. Any way to make it work?

I am using asar 0.8.2

**Comment by paulcbetts** [comment]
When you pass paths to native code or in some other scenarios, you sometimes have to undo the ASAR fiction (i.e. `process.resourcesPath.replace("app.asar", "app.asar.unpacked")`)

**Comment by luizlago** [comment]
I did just that some minutes ago! thanks :)
