### ISSUE TITLE
How to start asar on windows?

### ISSUE THREAD

**Issue by SteffenIvanhoe** [atom/asar#49]
I'm new to node and javascript. I have installed asar in Windows 7 via "npm install asar". But how can I start it? "asar --help" does not do it. "asar" is not in path. I can only find an "asar.js" but no exe file. How to use this tool in Windows 7?

**Comment by martinstarman** [comment]
Run ```npm install -g asar``` and then ```asar``` command should work.

**Comment by SteffenIvanhoe** [comment]
Thank you!
