### ISSUE TITLE
Does Windows' file path length limit apply to files in the archive?

### ISSUE THREAD

**Issue by adam-lynch** [atom/asar#53]
I mean how Windows has a 256 character limit on file paths. This has caused a lot of issues in the past with NW.js and I'm sure it must be the same with Electron. I wonder is using asar a workaround? I'm not sure how asar works though. If a file is requested in the archive, does it then at some point actually exist on disk with that file path?

**Comment by paulcbetts** [comment]
ASAR 100% solves this issue, MAX_PATH doesn't apply

**Comment by adam-lynch** [comment]
Wow cool.
