### ISSUE TITLE
Excluding file extensions?

### ISSUE THREAD

**Issue by PokemonAshLovesMyTurkeyAndILikeYouTwo** [atom/asar#56]
possible? :)

**Comment by PokemonAshLovesMyTurkeyAndILikeYouTwo** [comment]
I am wanting to basically pack my entire web directory but don't want to include all my .php source code stuff lol.

**Comment by lee-dohm** [comment]
Check the [README](https://github.com/atom/asar) ... it looks like it uses standard file globs, so this should work:

```
$ asar pack app app.asar --unpack-dir "**/*.php"
```
