### ISSUE TITLE
Order of files in archive varies each time 

### ISSUE THREAD

**Issue by bwin** [atom/asar#6]
This makes testing impossible.

**Comment by YuriSolovyov** [comment]
Hey @bwin are you still going to submit a PR about replacing `walkdir` with `glob` ?
It seems to be reliable and better maintaied.
I also solved some data races in my build process, with https://github.com/bwin/asar/commit/308d5cae8a4698543c97cd8fbf0da77d39172b19

**Comment by bwin** [comment]
Hi Yuri,
I settled for sorting the walkdir results (it's faster than glob). That's already merged.

**Comment by bwin** [comment]
I'm also still working on a complete rewrite of this repo (in tandem with the asar-part in atom-shell)...

**Comment by bwin** [comment]
> I also solved some data races in my build process, with bwin@308d5ca

Please tell me more.

**Comment by YuriSolovyov** [comment]
I just had an issue with asar JS API not working correctly:
sometimes it not included some files or folders in archive, so I tried to replace walkdir with glob and it seems it work better, but I need to spend more time with it to be sure.

>I'm also still working on a complete rewrite of this repo (in tandem with the asar-part in atom-shell)...

Are you goind to submit a PR or something? or just fork?
> Please tell me more.

I'm using [this](https://gist.github.com/YuriSolovyov/d56ba1128a8f83a0c70f)script to build my app.
Sometimes it builds just fine, and sometimes some files are missing. I still not sure what causes itm but again, it seems to work better with glob.

**Comment by bwin** [comment]
Sorry for the delay, went out to eat something.

> Are you going to submit a PR or something? or just fork?

PR (so it's zcbenz who decides if it makes it in, and if not then it'll be fork)

> Sometimes it builds just fine, and sometimes some files are missing.

There are two things I can think of (right now) that can go wrong.
- You reach some kind of path-depth limit. (But that would probably fail every time.)
- Or the asar API calls your callback too early.

Ok, I looked at bwin@308d5ca and saw this:
```javascript
disk.writeFilesystem(dest, filesystem, files);
...

// vs.

disk.writeFilesystem(dest, filesystem, files, function() { ...
```

The callback gets called prematurely (without waiting for disk.writeFilesystem to finish).
~~I'll fix it.~~
Hmm, it's already fixed in master.

Do you use the latest version of asar? Probably.

**Comment by YuriSolovyov** [comment]
@bwin 
> You reach some kind of path-depth limit. (But that would probably fail every time.)

no, folder structure is pretty flat, 5 nesting levels max.

>  Or the asar API calls your callback too early.

This might be the case, because I don't see any pattern in what files got skipped.
